name: Git Pull, Build, and Deploy on VPS
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: git pull, build, and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: | 
            cd ~/projects/muhrizqiardi.me/
            git pull
            yarn build
            pm2 restart @